name: book_club
description: A new Flutter project.

publish_to: 'none' 

version: 0.3.0+35

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  
  animations: ^2.0.7
  fluttertoast: ^8.2.2
  animate_icons: ^2.0.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  rive: ^0.11.6
  animated_text_kit: ^4.2.2

  uuid: ^3.0.7
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/rive/

  fonts: 
    - family: Lugrasimo
      fonts: 
        - asset: fonts/Lugrasimo-Regular.ttf

    - family: SeptemberScript
      fonts: 
        - asset: fonts/SeptemberScript.ttf

    - family: Rajdhani
      fonts: 
        - asset: fonts/Rajdhani/Rajdhani-Bold.ttf
          weight: 700
        - asset: fonts/Rajdhani/Rajdhani-Light.ttf
          weight: 300
        - asset: fonts/Rajdhani/Rajdhani-Medium.ttf
          weight: 500
        - asset: fonts/Rajdhani/Rajdhani-Regular.ttf
          weight: 400
        - asset: fonts/Rajdhani/Rajdhani-Semibold.ttf
          weight: 600

    - family: Quicksand
      fonts: 
        - asset: fonts/Quicksand/static/Quicksand-Bold.ttf
          weight: 700
        - asset: fonts/Quicksand/static/Quicksand-Light.ttf
          weight: 300
        - asset: fonts/Quicksand/static/Quicksand-Medium.ttf
          weight: 500
        - asset: fonts/Quicksand/static/Quicksand-Regular.ttf
          weight: 400
        - asset: fonts/Quicksand/static/Quicksand-Semibold.ttf
          weight: 600
