name: book_club
description: A new Flutter project.

publish_to: 'none' 

version: 0.0.11+21

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  shared_preferences: ^2.0.18
  animations: ^2.0.7
  fluttertoast: ^8.2.2
  animate_icons: ^2.0.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts: 
    - family: Lugrasimo
      fonts: 
        - asset: fonts/Lugrasimo-Regular.ttf