// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADwHxMkA0Bs-liE57tHQtHw-RFZsIAAgU',
    appId: '1:920810654162:web:b62f894c4c2a23207ee00b',
    messagingSenderId: '920810654162',
    projectId: 'book-club-9d684',
    authDomain: 'book-club-9d684.firebaseapp.com',
    storageBucket: 'book-club-9d684.appspot.com',
    measurementId: 'G-29NPQRY5NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwjPSGxIF3GYH6BWvctfBdbsfUXn6azN0',
    appId: '1:920810654162:android:94d8758253b3bb957ee00b',
    messagingSenderId: '920810654162',
    projectId: 'book-club-9d684',
    storageBucket: 'book-club-9d684.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKgINzI5jnGzNTQTQafKZgOn8Tjlas2IM',
    appId: '1:920810654162:ios:adaf12ac2d676f957ee00b',
    messagingSenderId: '920810654162',
    projectId: 'book-club-9d684',
    storageBucket: 'book-club-9d684.appspot.com',
    iosClientId: '920810654162-b9mtnvf7sjv9vcnjd5dik1kj0k1tiv9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKgINzI5jnGzNTQTQafKZgOn8Tjlas2IM',
    appId: '1:920810654162:ios:1350736122fdd7c07ee00b',
    messagingSenderId: '920810654162',
    projectId: 'book-club-9d684',
    storageBucket: 'book-club-9d684.appspot.com',
    iosClientId: '920810654162-t54gco3b437gpv5clqc5c35hh41vc6u4.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookClub.RunnerTests',
  );
}
